# Generated by Django 3.1.1 on 2022-01-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_images_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
