# Generated by Django 3.1.1 on 2022-01-31 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_images_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='picture',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=''),
        ),
    ]
